export { default as Home } from "./home/Home";
export { default as MyArchiNfts } from "./myArchiNfts/MyArchiNfts";
export { default as MyListing } from "./myListing/MyListing";
export { default as Create } from "./create/Create";
export { default as Login } from "./login/Login";
export { default as Register } from "./register/Register";
export { default as Nftitem } from "./nftitem/Nftitem";
export { default as Biditem } from "./biditem/Biditem";
export { default as Archimint } from "./archiMint/Archimint";
